In [9]:
import torch
print(torch.__version__)

2.0.0+cpu


In [10]:
import torch
x = torch.arange(1.,11.)
x

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [11]:
z = x.view(1,10)
x, z

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]))

In [17]:
x = torch.arange(1,10).reshape(1,3,3)
x
x[:,:,1]

tensor([[2, 5, 8]])